# Generated by Django 3.2.7 on 2023-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230211_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_caught_function', models.CharField(default='', max_length=40)),
                ('error_message', models.CharField(default='', max_length=100)),
                ('error_caught_user', models.CharField(default='', max_length=40)),
                ('error_caught_date', models.DateTimeField(auto_now=True, max_length=10)),
            ],
        ),
    ]
